import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import NextUIProvider from '@/providers/next-ui-provider'
import MainNavbar from '@/components/main-navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SpeechScheduler',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <NextUIProvider>
          <main className="dark text-foreground bg-background">
              {children}
            </main>
          </NextUIProvider>
        </body>
      </html>
  )
}
